### ISSUE TITLE
 It's not possible to open the repository to copy the code.

### ISSUE THREAD

**Issue by DinisMendes** [AlexCork1/SmartHome#1]
It is not possible to open the repository to copy the code. 
Would it be possible to resolve this small issue? 
I would be very grateful. 
Thank you.
![Opera Instantâneo_2024-01-30_114837_github com](https://github.com/AlexCork1/SmartHome/assets/155547566/018e167c-fe2d-4b06-b222-231f5c33db45)

**Comment by AlexCork1** [comment]
Fixed. Thank you
