### ISSUE TITLE
Hello, I need a little help

### ISSUE THREAD

**Issue by DinisMendes** [AlexCork1/SmartHome#2]
Hello, I need help. I have to do a project for school with Arduino, and I'm new to the Arduino world. I ventured into this Keystudio KS5009 project, and due to little research, I didn't think it would be so difficult. Could you try to help me? Explaining how libraries work and how to run the code? Because I don't understand anything about the (.h) and (.cpp) files. Thank you; it would be a huge help for me.

**Comment by AlexCork1** [comment]
https://www.geeksforgeeks.org/header-files-in-c-cpp-and-its-uses/
https://www.youtube.com/watch?v=ru_u9N7jydU
and many more on YT and Google
